export const WATCH_SIMPLE_TYPES = 'WATCH_SIMPLE_TYPES';

export const SIMPLE_TYPES_START = 'SIMPLE_TYPES_START';
export const SIMPLE_TYPES_SUCCESS = 'SIMPLE_TYPES_SUCCESS';
export const SIMPLE_TYPES_FAILURE = 'SIMPLE_TYPES_FAILURE';

export const WATCH_REGISTER = 'WATCH_REGISTER';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const WATCH_VERIFICATION = 'WATCH_VERIFICATION';

export const VERIFICATION_START = 'VERIFICATION_START';
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAILURE = 'VERIFICATION_FAILURE';

export const WATCH_PROVIDER = 'WATCH_PROVIDER';

export const PROVIDER_START = 'PROVIDER_START';
export const PROVIDER_SUCCESS = 'PROVIDER_SUCCESS';
export const PROVIDER_FAILURE = 'PROVIDER_FAILURE';