export const WATCH_GET_BLOGS = 'WATCH_GET_BLOGS'
export const GET_BLOGS_START = 'GET_BLOGS_START'
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS'
export const GET_BLOGS_FAILURE = 'GET_BLOGS_FAILURE'

export const WATCH_GET_POST = 'WATCH_GET_POST'
export const GET_POST_START = 'GET_POST_START'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'
export const GET_POST_FAILURE = 'GET_POST_FAILURE'

export const WATCH_LIKE_UNLIKE_POST = 'WATCH_LIKE_UNLIKE_POST'
export const LIKE_UNLIKE_POST_START = 'LIKE_UNLIKE_POST_START'
export const LIKE_UNLIKE_POST_SUCCESS = 'LIKE_UNLIKE_POST_SUCCESS'
export const LIKE_UNLIKE_POST_FAILURE = 'LIKE_UNLIKE_POST_FAILURE'