export const WATCH_GET_SUBCATEGORY_BY_CATEGORY = 'WATCH_GET_SUBCATEGORY_BY_CATEGORY'
export const GET_SUBCATEGORY_BY_CATEGORY_START = 'GET_SUBCATEGORY_BY_CATEGORY_START'
export const GET_SUBCATEGORY_BY_CATEGORY_SUCCESS = 'GET_SUBCATEGORY_BY_CATEGORY_SUCCESS'
export const GET_SUBCATEGORY_BY_CATEGORY_FAILURE = 'GET_SUBCATEGORY_BY_CATEGORY_FAILURE'

export const WATCH_GET_DURATION_BY_YEAR = 'WATCH_GET_DURATION_BY_YEAR'
export const GET_DURATION_BY_YEAR_START = 'GET_DURATION_BY_YEAR_START'
export const GET_DURATION_BY_YEAR_SUCCESS = 'GET_DURATION_BY_YEAR_SUCCESS'
export const GET_DURATION_BY_YEAR_FAILURE = 'GET_DURATION_BY_YEAR_FAILURE'

export const WATCH_GET_MAIN_CATEGORIES = 'WATCH_GET_MAIN_CATEGORIES'
export const GET_MAIN_CATEGORIES_START = 'GET_MAIN_CATEGORIES_START'
export const GET_MAIN_CATEGORIES_SUCCESS = 'GET_MAIN_CATEGORIES_SUCCESS'
export const GET_MAIN_CATEGORIES_FAILURE = 'GET_MAIN_CATEGORIES_FAILURE'

export const WATCH_GET_CATEGORY = 'WATCH_GET_CATEGORY'
export const GET_CATEGORY_START = 'GET_CATEGORY_START'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE'

export const WATCH_GET_CITY_BY_AREA = 'WATCH_GET_CITY_BY_AREA'
export const GET_CITY_BY_AREA_START = 'GET_CITY_BY_AREA_START'
export const GET_CITY_BY_AREA_SUCCESS = 'GET_CITY_BY_AREA_SUCCESS'
export const GET_CITY_BY_AREA_FAILURE = 'GET_CITY_BY_AREA_FAILURE'

export const WATCH_GET_SUBCATEGORY = 'WATCH_GET_SUBCATEGORY'
export const GET_SUBCATEGORY_START = 'GET_SUBCATEGORY_START'
export const GET_SUBCATEGORY_SUCCESS = 'GET_SUBCATEGORY_SUCCESS'
export const GET_SUBCATEGORY_FAILURE = 'GET_SUBCATEGORY_FAILURE'

export const WATCH_GET_AREAS = 'WATCH_GET_AREAS'
export const GET_AREAS_START = 'GET_AREAS_START'
export const GET_AREAS_SUCCESS = 'GET_AREAS_SUCCESS'
export const GET_AREAS_FAILURE = 'GET_AREAS_FAILURE'
