export const WATCH_GET_CONVERSATIONS = 'WATCH_GET_CONVERSATIONS'
export const GET_CONVERSATIONS_START = 'GET_CONVERSATIONS_START'
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS'
export const GET_CONVERSATIONS_FAILURE = 'GET_CONVERSATIONS_FAILURE'

export const WATCH_GET_MESSAGES = 'WATCH_GET_MESSAGES'
export const GET_MESSAGES_START = 'GET_MESSAGES_START'
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_FAILURE = 'GET_MESSAGES_FAILURE'

export const WATCH_OPEN_CONVERSATION = 'WATCH_OPEN_CONVERSATION'
export const OPEN_CONVERSATION_START = 'OPEN_CONVERSATION_START'
export const OPEN_CONVERSATION_SUCCESS = 'OPEN_CONVERSATION_SUCCESS'
export const OPEN_CONVERSATION_FAILURE = 'OPEN_CONVERSATION_FAILURE'

export const WATCH_CREATE_MESSAGE = 'WATCH_CREATE_MESSAGE'
export const CREATE_MESSAGE_START = 'CREATE_MESSAGE_START'
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS'
export const CREATE_MESSAGE_FAILURE = 'CREATE_MESSAGE_FAILURE'

// export const WATCH_CHATS_CHANNEL = 'WATCH_CHATS_CHANNEL'
export const CHATS_CHANNEL_ON = 'CHATS_CHANNEL_ON'
export const CHATS_CHANNEL_LISTENER = 'CHATS_CHANNEL_LISTENER'
export const CHATS_CHANNEL_ERROR = 'CHATS_CHANNEL_ERROR'