export const WATCH_GET_ALL_FAQ = 'WATCH_GET_ALL_FAQ'
export const GET_ALL_FAQ_START = 'GET_ALL_FAQ_START'
export const GET_ALL_FAQ_SUCCESS = 'GET_ALL_FAQ_SUCCESS'
export const GET_ALL_FAQ_FAILURE = 'GET_ALL_FAQ_FAILURE'

export const WATCH_ADD_QUESTION = 'WATCH_ADD_QUESTION'
export const ADD_QUESTION_START = 'ADD_QUESTION_START'
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS'
export const ADD_QUESTION_FAILURE = 'ADD_QUESTION_FAILURE'

export const WATCH_FIRST_ANSWER = 'WATCH_FIRST_ANSWER'
export const FIRST_ANSWER_START = 'FIRST_ANSWER_START'
export const FIRST_ANSWER_SUCCESS = 'FIRST_ANSWER_SUCCESS'
export const FIRST_ANSWER_FAILURE = 'FIRST_ANSWER_FAILURE'

export const WATCH_ANSWER_BACK = 'WATCH_ANSWER_BACK'
export const ANSWER_BACK_START = 'ANSWER_BACK_START'
export const ANSWER_BACK_SUCCESS = 'ANSWER_BACK_SUCCESS'
export const ANSWER_BACK_FAILURE = 'ANSWER_BACK_FAILURE'

export const WATCH_SEND_FORM = 'WATCH_SEND_FORM'
export const SEND_FORM_START = 'SEND_FORM_START'
export const SEND_FORM_SUCCESS = 'SEND_FORM_SUCCESS'
export const SEND_FORM_FAILURE = 'SEND_FORM_FAILURE'