export const WATCH_GET_HR_ACCOUNT = 'WATCH_GET_HR_ACCOUNT';
export const GET_HR_ACCOUNT_START = 'GET_HR_ACCOUNT_START';
export const GET_HR_ACCOUNT_SUCCESS = 'GET_HR_ACCOUNT_SUCCESS';
export const GET_HR_ACCOUNT_FAILURE = 'GET_HR_ACCOUNT_FAILURE';

export const WATCH_STORE_HR_ACCOUNT = 'WATCH_STORE_HR_ACCOUNT';
export const STORE_HR_ACCOUNT_START = 'STORE_HR_ACCOUNT_START';
export const STORE_HR_ACCOUNT_SUCCESS = 'STORE_HR_ACCOUNT_SUCCESS';
export const STORE_HR_ACCOUNT_FAILURE = 'STORE_HR_ACCOUNT_FAILURE';
