export const WATCH_GET_JOBS = 'WATCH_GET_JOBS';
export const GET_JOBS_START = 'GET_JOBS_START';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_FAILURE = 'GET_JOBS_FAILURE';

export const GET_SERACH_JOBS_SUCCESS = 'GET_SEARCH_JOBS_SUCCESS'

export const WATCH_GET_FOVORITE_JOB = 'WATCH_GET_FOVORITE_JOB';
export const GET_FOVORITE_JOB_START = 'GET_FOVORITE_JOB_START';
export const GET_FOVORITE_JOB_SUCCESS = 'GET_FOVORITE_JOB_SUCCESS';
export const GET_FOVORITE_JOB_FAILURE = 'GET_FOVORITE_JOB_FAILURE';

export const WATCH_GET_FILTERED_JOBS = 'WATCH_GET_FILTERED_JOBS';
export const GET_FILTERED_JOBS_START = 'GET_FILTERED_JOBS_START';
export const GET_FILTERED_JOBS_SUCCESS = 'GET_FILTERED_JOBS_SUCCESS';
export const GET_FILTERED_JOBS_FAILURE = 'GET_FILTERED_JOBS_FAILURE';

export const WATCH_VIEW_JOB = 'WATCH_VIEW_JOB';
export const VIEW_JOB_START = 'VIEW_JOB_START';
export const VIEW_JOB_SUCCESS = 'VIEW_JOB_SUCCESS';
export const VIEW_JOB_FAILURE = 'VIEW_JOB_FAILURE';

export const WATCH_APPLY_JOB = 'WATCH_APPLY_JOB';
export const APPLY_JOB_START = 'APPLY_JOB_START';
export const APPLY_JOB_SUCCESS = 'APPLY_JOB_SUCCESS';
export const APPLY_JOB_FAILURE = 'APPLY_JOB_FAILURE';