// export const WATCH_NOTIFICATIONS_CHANNEL = 'WATCH_NOTIFICATIONS_CHANNEL'
export const NOTIFICATIONS_CHANNEL_ON = 'NOTIFICATIONS_CHANNEL_ON'
export const NOTIFICATIONS_CHANNEL_LISTENER = 'NOTIFICATIONS_CHANNEL_LISTENER'
export const NOTIFICATIONS_CHANNEL_ERROR = 'NOTIFICATIONS_CHANNEL_ERROR'
