export const WATCH_GET_OPPORTUNITIES = 'WATCH_GET_OPPORTUNITIES';
export const GET_OPPORTUNITIES_START = 'GET_OPPORTUNITIES_START';
export const GET_OPPORTUNITIES_SUCCESS = 'GET_OPPORTUNITIES_SUCCESS';
export const GET_OPPORTUNITIES_FAILURE = 'GET_OPPORTUNITIES_FAILURE';

export const WATCH_UPDATE_JOB_STATUS = 'WATCH_UPDATE_JOB_STATUS';
export const UPDATE_JOB_STATUS_START = 'UPDATE_JOB_STATUS_START';
export const UPDATE_JOB_STATUS_SUCCESS = 'UPDATE_JOB_STATUS_SUCCESS';
export const UPDATE_JOB_STATUS_FAILURE = 'UPDATE_JOB_STATUS_FAILURE';

export const WATCH_GET_CONTENDERS = 'WATCH_GET_CONTENDERS';
export const GET_CONTENDERS_START = 'GET_CONTENDERS_START';
export const GET_CONTENDERS_SUCCESS = 'GET_CONTENDERS_SUCCESS';
export const GET_CONTENDERS_FAILURE = 'GET_CONTENDERS_FAILURE';

export const WATCH_GET_OPPORTUNITY_PAGE = 'WATCH_GET_OPPORTUNITY_PAGE';
export const GET_OPPORTUNITY_PAGE_START = 'GET_OPPORTUNITY_PAGE_START';
export const GET_OPPORTUNITY_PAGE_SUCCESS = 'GET_OPPORTUNITY_PAGE_SUCCESS';
export const GET_OPPORTUNITY_PAGE_FAILURE = 'GET_OPPORTUNITY_PAGE_FAILURE';

export const WATCH_GET_OPPORTUNITY_VIEW = 'WATCH_GET_OPPORTUNITY_VIEW';
export const GET_OPPORTUNITY_VIEW_START = 'GET_OPPORTUNITY_VIEW_START';
export const GET_OPPORTUNITY_VIEW_SUCCESS = 'GET_OPPORTUNITY_VIEW_SUCCESS';
export const GET_OPPORTUNITY_VIEW_FAILURE = 'GET_OPPORTUNITY_VIEW_FAILURE';

export const WATCH_GET_OPPORTUNITY_TYPE_DATA = 'WATCH_GET_OPPORTUNITY_TYPE_DATA';
export const GET_OPPORTUNITY_TYPE_DATA_START = 'GET_OPPORTUNITY_TYPE_DATA_START';
export const GET_OPPORTUNITY_TYPE_DATA_SUCCESS = 'GET_OPPORTUNITY_TYPE_DATA_SUCCESS';
export const GET_OPPORTUNITY_TYPE_DATA_FAILURE = 'GET_OPPORTUNITY_TYPE_DATA_FAILURE';

export const WATCH_CREATE_OPPORTUNITY = 'WATCH_CREATE_OPPORTUNITY';
export const CREATE_OPPORTUNITY_START = 'CREATE_OPPORTUNITY_START';
export const CREATE_OPPORTUNITY_SUCCESS = 'CREATE_OPPORTUNITY_SUCCESS';
export const CREATE_OPPORTUNITY_FAILURE = 'CREATE_OPPORTUNITY_FAILURE';

export const WATCH_CREATE_OPPORTUNITY_MIDRASHA = 'WATCH_CREATE_OPPORTUNITY_MIDRASHA';
export const CREATE_OPPORTUNITY_MIDRASHA_START = 'CREATE_OPPORTUNITY_MIDRASHA_START';
export const CREATE_OPPORTUNITY_MIDRASHA_SUCCESS = 'CREATE_OPPORTUNITY_MIDRASHA_SUCCESS';
export const CREATE_OPPORTUNITY_MIDRASHA_FAILURE = 'CREATE_OPPORTUNITY_MIDRASHA_FAILURE';

export const WATCH_GET_EXISTING_OPPORTUNITY = 'WATCH_GET_EXISTING_OPPORTUNITY';
export const GET_EXISTING_OPPORTUNITY_START = 'GET_EXISTING_OPPORTUNITY_START';
export const GET_EXISTING_OPPORTUNITY_SUCCESS = 'GET_EXISTING_OPPORTUNITY_SUCCESS';
export const GET_EXISTING_OPPORTUNITY_FAILURE = 'GET_EXISTING_OPPORTUNITY_FAILURE';

export const WATCH_UPDATE_OPPORTUNITY = 'WATCH_UPDATE_OPPORTUNITY';
export const UPDATE_OPPORTUNITY_START = 'UPDATE_OPPORTUNITY_START';
export const UPDATE_OPPORTUNITY_SUCCESS = 'UPDATE_OPPORTUNITY_SUCCESS';
export const UPDATE_OPPORTUNITY_FAILURE = 'UPDATE_OPPORTUNITY_FAILURE';

export const WATCH_GET_CHOSEN_CONTENDERS = 'WATCH_GET_CHOSEN_CONTENDERS';
export const GET_CHOSEN_CONTENDERS_START = 'GET_CHOSEN_CONTENDERS_START';
export const GET_CHOSEN_CONTENDERS_SUCCESS = 'GET_CHOSEN_CONTENDERS_SUCCESS';
export const GET_CHOSEN_CONTENDERS_FAILURE = 'GET_CHOSEN_CONTENDERS_FAILURE';

export const WATCH_GET_CONTENDER_PROFILE = 'WATCH_GET_CONTENDER_PROFILE';
export const GET_CONTENDER_PROFILE_START = 'GET_CONTENDER_PROFILE_START';
export const GET_CONTENDER_PROFILE_SUCCESS = 'GET_CONTENDER_PROFILE_SUCCESS';
export const GET_CONTENDER_PROFILE_FAILURE = 'GET_CONTENDER_PROFILE_FAILURE';

export const WATCH_UPDATE_CONTENDER_STATUS = 'WATCH_UPDATE_CONTENDER_STATUS';
export const UPDATE_CONTENDER_STATUS_START = 'UPDATE_CONTENDER_STATUS_START';
export const UPDATE_CONTENDER_STATUS_SUCCESS = 'UPDATE_CONTENDER_STATUS_SUCCESS';
export const UPDATE_CONTENDER_STATUS_FAILURE = 'UPDATE_CONTENDER_STATUS_FAILURE';