export const WATCH_GET_LIST_OF_REQUESTS = 'WATCH_GET_LIST_OF_REQUESTS'
export const GET_LIST_OF_REQUESTS_START = 'GET_LIST_OF_REQUESTS_START'
export const GET_LIST_OF_REQUESTS_SUCCESS = 'GET_LIST_OF_REQUESTS_SUCCESS'
export const GET_LIST_OF_REQUESTS_FAILURE = 'GET_LIST_OF_REQUESTS_FAILURE'

export const WATCH_GET_FAVORITE_JOBS = 'WATCH_GET_FAVORITE_JOBS'
export const GET_FAVORITE_JOBS_START = 'GET_FAVORITE_JOBS_START'
export const GET_FAVORITE_JOBS_SUCCESS = 'GET_FAVORITE_JOBS_SUCCESS'
export const GET_FAVORITE_JOBS_FAILURE = 'GET_FAVORITE_JOBS_FAILURE'

export const WATCH_GET_INFO_FOR_PROFILE = 'WATCH_GET_INFO_FOR_PROFILE'
export const GET_INFO_FOR_PROFILE_START = 'GET_INFO_FOR_PROFILE_START'
export const GET_INFO_FOR_PROFILE_SUCCESS = 'GET_INFO_FOR_PROFILE_SUCCESS'
export const GET_INFO_FOR_PROFILE_FAILURE = 'GET_INFO_FOR_PROFILE_FAILURE'

export const WATCH_CREATE_NEW_SCHOOL = 'WATCH_CREATE_NEW_SCHOOL'
export const CREATE_NEW_SCHOOL_START = 'CREATE_NEW_SCHOOL_START'
export const CREATE_NEW_SCHOOL_SUCCESS = 'CREATE_NEW_SCHOOL_SUCCESS'
export const CREATE_NEW_SCHOOL_FAILURE = 'CREATE_NEW_SCHOOL_FAILURE'

export const WATCH_STORE_ADDITIONAL_INFO = 'WATCH_STORE_ADDITIONAL_INFO'
export const STORE_ADDITIONAL_INFO_START = 'STORE_ADDITIONAL_INFO_START'
export const STORE_ADDITIONAL_INFO_SUCCESS = 'STORE_ADDITIONAL_INFO_SUCCESS'
export const STORE_ADDITIONAL_INFO_FAILURE = 'STORE_ADDITIONAL_INFO_FAILURE'

export const WATCH_STORE_BIRTHDAY_INFO = 'WATCH_STORE_BIRTHDAY_INFO'
export const STORE_BIRTHDAY_INFO_START = 'STORE_BIRTHDAY_INFO_START'
export const STORE_BIRTHDAY_INFO_SUCCESS = 'STORE_BIRTHDAY_INFO_SUCCESS'
export const STORE_BIRTHDAY_INFO_FAILURE = 'STORE_BIRTHDAY_INFO_FAILURE'

export const WATCH_CREATE_NEW_CITY = 'WATCH_CREATE_NEW_CITY'
export const CREATE_NEW_CITY_START = 'CREATE_NEW_CITY_START'
export const CREATE_NEW_CITY_SUCCESS = 'CREATE_NEW_CITY_SUCCESS'
export const CREATE_NEW_CITY_FAILURE = 'CREATE_NEW_CITY_FAILURE'

export const WATCH_STORE_DETAILS = 'WATCH_STORE_DETAILS'
export const STORE_DETAILS_START = 'STORE_DETAILS_START'
export const STORE_DETAILS_SUCCESS = 'STORE_DETAILS_SUCCESS'
export const STORE_DETAILS_FAILURE = 'STORE_DETAILS_FAILURE'