export const WATCH_GET_QUIZ = 'WATCH_GET_QUIZ';

export const GET_QUIZ_START = 'GET_QUIZ_START';
export const GET_QUIZ_SUCCES = 'GET_QUIZ_SUCCES';
export const GET_QUIZ_FAILURE = 'GET_QUIZ_FAILURE';

export const WATCH_SET_QUIZ = 'WATCH_SET_QUIZ';

export const SET_QUIZ_START = 'SET_QUIZ_START';
export const SET_QUIZ_SUCCES = 'SET_QUIZ_SUCCES';
export const SET_QUIZ_FAILURE = 'SET_QUIZ_FAILURE';

export const WATCH_QUIZ_RESULT = 'WATCH_QUIZ_RESULT';

export const QUIZ_RESULT_START = 'QUIZ_RESULT_START';
export const QUIZ_RESULT_SUCCES = 'QUIZ_RESULT_SUCCES';
export const QUIZ_RESULT_FAILURE = 'QUIZ_RESULT_FAILURE';