export const WATCH_GET_REVIEWS = 'WATCH_GET_REVIEWS'
export const GET_REVIEWS_START = 'GET_REVIEWS_START'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE'

export const WATCH_GET_REVIEWS_DATA = 'WATCH_GET_REVIEWS_DATA'
export const GET_REVIEWS_DATA_START = 'GET_REVIEWS_DATA_START'
export const GET_REVIEWS_DATA_SUCCESS = 'GET_REVIEWS_DATA_SUCCESS'
export const GET_REVIEWS_DATA_FAILURE = 'GET_REVIEWS_DATA_FAILURE'

export const WATCH_STORE_REVIEW = 'WATCH_STORE_REVIEW'
export const STORE_REVIEW_START = 'STORE_REVIEW_START'
export const STORE_REVIEW_SUCCESS = 'STORE_REVIEW_SUCCESS'
export const STORE_REVIEW_FAILURE = 'STORE_REVIEW_FAILURE'